# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run-script build --dest dist
  displayName: 'npm install and build'

- task : ArchiveFiles@2
  inputs :
    rootFolderOrFile : '$(Build.SourcesDirectory)/dist'
    includeRootFolder : false
    archiveType : 'zip'
    archiveFile : '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'
    replaceExistingArchive : true
  displayName : 'Archive artifact'

- task : PublishBuildArtifacts@1
  inputs :
    PathtoPublish : '$(Build.ArtifactStagingDirectory)'
    ArtifactName : 'drop'
    publishLocation : 'Container'
  displayName : 'Publish artifact'